### ISSUE TITLE
get the input 

### ISSUE THREAD

**Issue by helio-frota** [EsmerilProgramming/hb#1]

**Comment by eprogramming** [comment]
https://www.youtube.com/watch?v=4yRpysQxRxE

**Comment by htmfilho** [comment]
0100110101110101011010010111010001101111011100110010000001100001011011100110111101110011001000000110010001100101001000000111011001101001011001000110000100100000001110100010110100101001

**Comment by htmfilho** [comment]
010001100110010101101100011010010110001101101001011001000110000101100100011001010111001100100001

**Comment by eprogramming** [comment]
011101100110000101101101011011110111001100100000011101010111001101100001011100100010000001100001011100110111001101100101011011010110001001101100011110010010000001101110011001010111001101110011011001010010000001110000011100100110111101101010011001010111010001101111001000000000110100001010011011110010000001110000011100100110010101110011011001010110111001110100011001010010110000100000011100010111010101100101001000000110010101101000001000000110001001101111011011010010110000100000011001010111001101110001011101010110010101100011011010010010000001100100011001010010000001110100011100100110000101111010011001010111001000100000001110110010000001011101

**Comment by htmfilho** [comment]
https://www.youtube.com/watch?v=lmAOQ-hPqIE
01000101011011100111010001101001011100100110010101101100011110010010000001110111011100100110100101110100011101000110010101101110001000000110100101101110001000000110000101110011011100110110010101101101011000100110110001111001

**Comment by eprogramming** [comment]
011000010111011101100101011100110110111101101101011001010010000000100001

**Comment by eprogramming** [comment]
A lot of reading before get the input  ( i mean , trying to not use a piece of code from google results )
One thing is read about assembly, other thing is try to put in practice.
